---
build_from:
  aarch64: ghcr.io/hassio-addons/base:21.0.0
  amd64: ghcr.io/hassio-addons/base:21.0.0
args:
  APP_API_IMAGE: ghcr.io/eigger/stash-api:latest
  APP_WEB_IMAGE: ghcr.io/eigger/stash-web:latest
